### ISSUE TITLE
Could `Object.pickBy` be added, too?

### ISSUE THREAD

**Issue by isiahmeadows** [aleen42/proposal-object-pick-or-omit#2]
I would find myself using that as much as `Object.pick`/`Object.omit`.

**Comment by aleen42** [comment]
Of course, and `Object.omitBy` is corresponding for your request.

**Comment by isiahmeadows** [comment]
Of course. I've just got an absurd amount of `Object.fromEntries(Object.entries(object).filter(([, value]) => value.prop === whatever))` at work, and I know I'm not the only one dealing with such a general pattern. That obviously could be simplified to `Object.pickBy(object, (_, value) => value.prop === whatever)` with such an `Object.pickBy`, and it'd also mean engines wouldn't need to create two intermediate arrays just to do that (which would be really nice).

**Comment by aleen42** [comment]
Feel free to reopen it if you have any question around `Object.pickBy` and `Object.omitBy`.

**Comment by aleen42** [comment]
@gausie It should be the third one like: `Object.pick(obj, keysOrPredictions, byValue)`, and it seems too complicated to remember.

**Comment by theScottyJam** [comment]
I do know that an `Object.map()` function has been proposed to the committee in the past, and was ultimately rejected (see the proposal [here](https://github.com/tc39/proposal-object-iteration#october-2019), and a little more context [here](https://es.discourse.group/t/elaboration-on-why-the-committee-decided-not-to-add-an-object-map-method/684/2)). Ultimately, they didn't want to try and replicate all of the array utility functions for objects, and would rather have people use `Map` instead. `Object.pickBy()` sort of just feels like the `filter` function for arrays - as nice as that would be to add, I'm not sure if it'll actually get through.

**Comment by theScottyJam** [comment]
Oh, also, we probably don't need both an `Object.pickBy()` and an `Object.omitBy()`. You can simply emulate `Object.omitBy()` by negating the predicate passed into `Object.pickBy()`.

For example:

```javascript
// This:
const minors = Object.omitBy(users, user => user.adult)

// is the same as this:
const minors = Object.pickBy(users, user => !user.adult)
```

Let's follow Python's (claimed) philosophy on this matter:
> There should be one-- and preferably only one --obvious way to do it.

**Comment by aleen42** [comment]
@theScottyJam Your point can also apply to `Object.pick` and `Object.omit`:

```js
Object.omit(target, [key1, key2]);

// Equivalent to

Object.pick(target,
    Object.keys(target).filter(i => [key1, key2].includes(i));
```


In my opinion, native methods should have their clear meaning, and should not mix into one.

**Comment by theScottyJam** [comment]
Yes, that's true, that's why it's always a balancing act - does the usefulness of adding this new function outweigh the added bloat to Javascript's APIs? We obviously have differing opinions here, which is fine :).


However, I can't imagine that we would end up with both a pickBy and omitBy for objects, and yet have an array API that only contains a filter method, and not an omitIf method. (Have you ever felt like you needed an omitIf method? Has negating the predicate for the filter function ever felt cumbersome or less readable?) It would be inconsistent for TC39 to want both flavors for objects and only want one flavor with arrays.

But, that's just my opinion on it.

**Comment by aleen42** [comment]
@theScottyJam You're right. To some extent, it seems like an unnecessary definition when filtered methods can be easily reversed. How about naming it with another neutral word like `filterBy`?

**Comment by theScottyJam** [comment]
`filterBy` is another valid name for it, but I do like `pickBy` better. I actually wish `array.filter()` were named something like `array.select` or `array.pickBy` instead, as to this day, I still sometimes forget whether a truthy value will cause the element to be included (filtered for) or excluded (filtered out) from the results. A name like "pickBy" tells you while "filter" does not.

So, even in this example where the predicate has been negated, using the word `pickBy` still makes complete sense. In the following snippet, we're wanting to "pick out users where the user is not an adult", which semantically means the same thing as "omit users where the user is an adult".

```javascript
const minors = Object.pickBy(users, user => !user.adult)
```

**Comment by isiahmeadows** [comment]
@theScottyJam The same could be said about [filtering out of arrays](https://github.com/tc39/proposal-array-filtering). 😉

**Comment by aleen42** [comment]
@isiahmeadows Interesting philosophy for designing methods.

**Comment by isiahmeadows** [comment]
I'm more just saying apparent duplication isn't in of itself a valid reason to reject it. It does raise the bar, but not all the way to the ceiling.

**Comment by theScottyJam** [comment]
That's an interesting proposal.

Well, I did say

> It would be inconsistent for TC39 to want both flavors for objects while arrays only have a "pickBy" variant of the filter function.

so, if they do end up adding a `.filterOut` method for arrays, then it would become consistent for TC39 to also add a `omitBy` and my argument would dissapear. Though, the reasonings for adding `.filterBy()` has everything to do with the fact that `.filter()` is a confusing name, and little to do with the fact that they just wanted a negative form of `.filter()` - the same wouldn't be true with a name like `.pickBy()`.

**Comment by isiahmeadows** [comment]
It's also worth noting that of course names are extremely bikesheddable and are probably best to just defer for now (it's a bit early anyways).

**Comment by ljharb** [comment]
I would think that rather than double the methods, the second argument of omit/pick could be either a predicate function or an iterable.

**Comment by aleen42** [comment]
In my opinion, any decision made by the committee should obey developers' habits formed before. [Lodash](https://lodash.com/docs/4.17.15#pickBy) has separated two methods while [Underscore](https://underscorejs.org/#pick) has combined two into one argument. Giving a choice for developers to vote for might be a good choice, and is there any precedent?

I have met a similar case before where jQuery has defined the iterator functions: `$.each((key, value) => {})`, which ES has reversed former two arguments.

**Comment by ljharb** [comment]
Userland precedent informs, but never constrains, the language, and decisions aren't made by voting.

If they're separate methods, then the case needs to be made independently for all 4 methods (even though "consistency" would be an argument for all 4 if any of the 4 land). If they're the same methods, then you only need to make the case for 2, which is a much easier case to make.

**Comment by theScottyJam** [comment]
> I would think that rather than double the methods, the second argument of omit/pick could be either a predicate function or an iterable.

This seems reasonable to me as well. I wouldn't have a strong preference either way, but I do see an advantage to having less methods. It can be annoying when standard libraries have a gazillion different utility functions that you learn about (I'm mostly thinking about arrays here, but the same is true for any data type) - you love them when you use them, but looking at all of the options can be a bit overwhelming.

**Comment by aleen42** [comment]
This is similar to what we discussed before in https://es.discourse.group/t/immutable-objects/658, 
which is about the topic: should we define different methods or combine into one method with different arguments about `Object.{freeze, seal, preventExtensions}`?

**Comment by ljharb** [comment]
That certainly would have been a different potential design, but it’s not worth making redundant methods now.

**Comment by aleen42** [comment]
Agree with it, I will update the draft tomorrow.

**Comment by dead-claudia** [comment]
@ljharb 

> I would think that rather than double the methods, the second argument of omit/pick could be either a predicate function or an iterable.

Just to reiterate: https://github.com/aleen42/proposal-object-pick-or-omit/issues/2#issuecomment-880212463 I'm more concerned about functionality than naming. I'm okay with it being an overload instead.
